from __future__ import annotations

import json

from skillpilot.models import SkillResourceSpec, SkillSpec
from skillpilot.skills.core import LLMProvider
from skillpilot.utils import extract_json_object


class ResourceGenerator:
    def __init__(self, llm: LLMProvider | None = None) -> None:
        self.llm = llm

    def render(self, file_spec: SkillResourceSpec, spec: SkillSpec) -> str:
        llm_content = self._render_with_llm(file_spec, spec)
        if llm_content:
            return llm_content
        if file_spec.path.endswith("guidance_rules.md"):
            return self._guidance_rules(spec)
        if file_spec.path.endswith("output_template.md"):
            return self._output_template(spec)
        if file_spec.path.startswith("examples/"):
            return self._sample_output(spec)
        if file_spec.path == "README.md":
            return self._readme(spec)
        if file_spec.path == "scripts/README.md":
            return self._scripts_readme(spec)
        return self._generic_resource(file_spec, spec)

    def _render_with_llm(self, file_spec: SkillResourceSpec, spec: SkillSpec) -> str:
        if self.llm is None or file_spec.path in {"README.md", "scripts/README.md"}:
            return ""
        prompt = (
            "你是 SkillPilot 的 ResourceGenerationSkill。请根据 SkillSpec 和文件说明生成一个可直接写入的 "
            "Markdown 资源文件正文。返回严格 JSON，不要 Markdown fence。字段：content。"
            "content 必须符合 path 和 content_hint，不要生成可执行脚本，不要要求用户提供密钥。\n"
            f"SkillSpec：{spec.model_dump()}\n"
            f"文件：{file_spec.model_dump()}"
        )
        try:
            response = self.llm.generate(prompt)
            payload = json.loads(extract_json_object(getattr(response, "text", str(response))))
        except Exception:  # noqa: BLE001 - static templates remain the safe fallback.
            return ""
        content = str(payload.get("content") or "").strip()
        if not content:
            return ""
        return content.rstrip() + "\n"

    def _guidance_rules(self, spec: SkillSpec) -> str:
        lines = [
            "# Guidance Rules",
            "",
            "## Purpose",
            "",
            spec.description,
            "",
            "## Required Boundaries",
            "",
        ]
        lines.extend(f"- {item}" for item in spec.constraints)
        lines.extend(["", "## Workflow Reminders", ""])
        lines.extend(f"{index}. {step}" for index, step in enumerate(spec.workflow, start=1))
        return "\n".join(lines).rstrip() + "\n"

    def _output_template(self, spec: SkillSpec) -> str:
        return f"""# Output Template

## Task Understanding

## Key Guidance

## Step-by-step Hints

## Suggested Output

{spec.output_format}

## Safety or Boundary Notes
"""

    def _sample_output(self, spec: SkillSpec) -> str:
        return f"""# Sample Output

## Task Understanding

I will handle this request using the `{spec.name}` workflow and keep the response inside the stated boundaries.

## Key Guidance

- Start by clarifying the goal and available source material.
- Follow the reusable workflow before producing the final answer.
- Check the final response against the constraints.

## Safety or Boundary Notes

This sample is intentionally generic. Replace it with a real project-specific example after manual review.
"""

    def _readme(self, spec: SkillSpec) -> str:
        notes = spec.packaging_notes or [
            "Review the generated files before using the Skill.",
            "Keep the Skill in a local skills directory appropriate for your Claude setup.",
        ]
        lines = [
            f"# {spec.name} Draft",
            "",
            "This directory was generated by SkillPilot as a draft custom Skill.",
            "",
            "## Files",
            "",
            "- `SKILL.md`: main Skill instructions.",
        ]
        lines.extend(f"- `{item.path}`: {item.purpose}" for item in spec.resources + spec.examples)
        lines.extend(["", "## Manual Review Notes", ""])
        lines.extend(f"- {item}" for item in notes)
        return "\n".join(lines).rstrip() + "\n"

    def _scripts_readme(self, spec: SkillSpec) -> str:
        lines = [
            "# Scripts Review",
            "",
            "This Skill requested script support, but SkillPilot does not auto-run generated scripts.",
            "Add scripts only after human review.",
            "",
            "## Notes",
            "",
        ]
        lines.extend(f"- {item}" for item in spec.script_notes or ["No script notes were provided."])
        return "\n".join(lines).rstrip() + "\n"

    def _generic_resource(self, file_spec: SkillResourceSpec, spec: SkillSpec) -> str:
        return f"""# {file_spec.purpose}

{file_spec.content_hint or "Use this resource to support the Skill workflow."}

Related Skill: {spec.name}
"""
